export enum ROUTES {
  ONBOARDING_STACK = 'ONBOARDING_STACK',
  ONBOARDING_SCREEN = 'ONBOARDING_SCREEN',
  SIGN_UP_STACK = 'SIGN_UP_STACK',
  SIGN_UP_STEP_ONE_SCREEN = 'SIGN_UP_STEP_ONE_SCREEN',
  SIGN_UP_STEP_TWO_SCREEN = 'SIGN_UP_STEP_TWO_SCREEN',
}
